/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkQueueRouteImport } from './routes/work-queue'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncorporationRouteImport } from './routes/incorporation'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AnnualReturnsRouteImport } from './routes/annual-returns'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappAutomationRouteImport } from './routes/whatsapp.automation'
import { Route as IncorporationIdRouteImport } from './routes/incorporation.$id'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as AnnualReturnsIdRouteImport } from './routes/annual-returns.$id'

const WorkQueueRoute = WorkQueueRouteImport.update({
  id: '/work-queue',
  path: '/work-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncorporationRoute = IncorporationRouteImport.update({
  id: '/incorporation',
  path: '/incorporation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualReturnsRoute = AnnualReturnsRouteImport.update({
  id: '/annual-returns',
  path: '/annual-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappAutomationRoute = WhatsappAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => WhatsappRoute,
} as any)
const IncorporationIdRoute = IncorporationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IncorporationRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const AnnualReturnsIdRoute = AnnualReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnualReturnsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annual-returns': typeof AnnualReturnsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/incorporation': typeof IncorporationRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRouteWithChildren
  '/work-queue': typeof WorkQueueRoute
  '/annual-returns/$id': typeof AnnualReturnsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/incorporation/$id': typeof IncorporationIdRoute
  '/whatsapp/automation': typeof WhatsappAutomationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annual-returns': typeof AnnualReturnsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/incorporation': typeof IncorporationRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRouteWithChildren
  '/work-queue': typeof WorkQueueRoute
  '/annual-returns/$id': typeof AnnualReturnsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/incorporation/$id': typeof IncorporationIdRoute
  '/whatsapp/automation': typeof WhatsappAutomationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annual-returns': typeof AnnualReturnsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/incorporation': typeof IncorporationRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRouteWithChildren
  '/work-queue': typeof WorkQueueRoute
  '/annual-returns/$id': typeof AnnualReturnsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/incorporation/$id': typeof IncorporationIdRoute
  '/whatsapp/automation': typeof WhatsappAutomationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annual-returns'
    | '/clients'
    | '/documents'
    | '/incorporation'
    | '/login'
    | '/payments'
    | '/portal'
    | '/settings'
    | '/whatsapp'
    | '/work-queue'
    | '/annual-returns/$id'
    | '/clients/$id'
    | '/incorporation/$id'
    | '/whatsapp/automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/annual-returns'
    | '/clients'
    | '/documents'
    | '/incorporation'
    | '/login'
    | '/payments'
    | '/portal'
    | '/settings'
    | '/whatsapp'
    | '/work-queue'
    | '/annual-returns/$id'
    | '/clients/$id'
    | '/incorporation/$id'
    | '/whatsapp/automation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annual-returns'
    | '/clients'
    | '/documents'
    | '/incorporation'
    | '/login'
    | '/payments'
    | '/portal'
    | '/settings'
    | '/whatsapp'
    | '/work-queue'
    | '/annual-returns/$id'
    | '/clients/$id'
    | '/incorporation/$id'
    | '/whatsapp/automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnualReturnsRoute: typeof AnnualReturnsRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  IncorporationRoute: typeof IncorporationRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  PortalRoute: typeof PortalRoute
  SettingsRoute: typeof SettingsRoute
  WhatsappRoute: typeof WhatsappRouteWithChildren
  WorkQueueRoute: typeof WorkQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-queue': {
      id: '/work-queue'
      path: '/work-queue'
      fullPath: '/work-queue'
      preLoaderRoute: typeof WorkQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incorporation': {
      id: '/incorporation'
      path: '/incorporation'
      fullPath: '/incorporation'
      preLoaderRoute: typeof IncorporationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-returns': {
      id: '/annual-returns'
      path: '/annual-returns'
      fullPath: '/annual-returns'
      preLoaderRoute: typeof AnnualReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/automation': {
      id: '/whatsapp/automation'
      path: '/automation'
      fullPath: '/whatsapp/automation'
      preLoaderRoute: typeof WhatsappAutomationRouteImport
      parentRoute: typeof WhatsappRoute
    }
    '/incorporation/$id': {
      id: '/incorporation/$id'
      path: '/$id'
      fullPath: '/incorporation/$id'
      preLoaderRoute: typeof IncorporationIdRouteImport
      parentRoute: typeof IncorporationRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/annual-returns/$id': {
      id: '/annual-returns/$id'
      path: '/$id'
      fullPath: '/annual-returns/$id'
      preLoaderRoute: typeof AnnualReturnsIdRouteImport
      parentRoute: typeof AnnualReturnsRoute
    }
  }
}

interface AnnualReturnsRouteChildren {
  AnnualReturnsIdRoute: typeof AnnualReturnsIdRoute
}

const AnnualReturnsRouteChildren: AnnualReturnsRouteChildren = {
  AnnualReturnsIdRoute: AnnualReturnsIdRoute,
}

const AnnualReturnsRouteWithChildren = AnnualReturnsRoute._addFileChildren(
  AnnualReturnsRouteChildren,
)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface IncorporationRouteChildren {
  IncorporationIdRoute: typeof IncorporationIdRoute
}

const IncorporationRouteChildren: IncorporationRouteChildren = {
  IncorporationIdRoute: IncorporationIdRoute,
}

const IncorporationRouteWithChildren = IncorporationRoute._addFileChildren(
  IncorporationRouteChildren,
)

interface WhatsappRouteChildren {
  WhatsappAutomationRoute: typeof WhatsappAutomationRoute
}

const WhatsappRouteChildren: WhatsappRouteChildren = {
  WhatsappAutomationRoute: WhatsappAutomationRoute,
}

const WhatsappRouteWithChildren = WhatsappRoute._addFileChildren(
  WhatsappRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnualReturnsRoute: AnnualReturnsRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  IncorporationRoute: IncorporationRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  PortalRoute: PortalRoute,
  SettingsRoute: SettingsRoute,
  WhatsappRoute: WhatsappRouteWithChildren,
  WorkQueueRoute: WorkQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
