/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AnnualReturnsRouteImport } from './routes/annual-returns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as AnnualReturnsIdRouteImport } from './routes/annual-returns.$id'

const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualReturnsRoute = AnnualReturnsRouteImport.update({
  id: '/annual-returns',
  path: '/annual-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const AnnualReturnsIdRoute = AnnualReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnualReturnsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annual-returns': typeof AnnualReturnsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/enquiries': typeof EnquiriesRoute
  '/annual-returns/$id': typeof AnnualReturnsIdRoute
  '/clients/$id': typeof ClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annual-returns': typeof AnnualReturnsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/enquiries': typeof EnquiriesRoute
  '/annual-returns/$id': typeof AnnualReturnsIdRoute
  '/clients/$id': typeof ClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annual-returns': typeof AnnualReturnsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/enquiries': typeof EnquiriesRoute
  '/annual-returns/$id': typeof AnnualReturnsIdRoute
  '/clients/$id': typeof ClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annual-returns'
    | '/clients'
    | '/enquiries'
    | '/annual-returns/$id'
    | '/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annual-returns'
    | '/clients'
    | '/enquiries'
    | '/annual-returns/$id'
    | '/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/annual-returns'
    | '/clients'
    | '/enquiries'
    | '/annual-returns/$id'
    | '/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnualReturnsRoute: typeof AnnualReturnsRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  EnquiriesRoute: typeof EnquiriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-returns': {
      id: '/annual-returns'
      path: '/annual-returns'
      fullPath: '/annual-returns'
      preLoaderRoute: typeof AnnualReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/annual-returns/$id': {
      id: '/annual-returns/$id'
      path: '/$id'
      fullPath: '/annual-returns/$id'
      preLoaderRoute: typeof AnnualReturnsIdRouteImport
      parentRoute: typeof AnnualReturnsRoute
    }
  }
}

interface AnnualReturnsRouteChildren {
  AnnualReturnsIdRoute: typeof AnnualReturnsIdRoute
}

const AnnualReturnsRouteChildren: AnnualReturnsRouteChildren = {
  AnnualReturnsIdRoute: AnnualReturnsIdRoute,
}

const AnnualReturnsRouteWithChildren = AnnualReturnsRoute._addFileChildren(
  AnnualReturnsRouteChildren,
)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnualReturnsRoute: AnnualReturnsRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  EnquiriesRoute: EnquiriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
